CREATE TABLE warehouse (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    location VARCHAR(255),
    max_space DOUBLE PRECISION
);

CREATE TABLE warehouse_zone (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    description VARCHAR(255),
    warehouse_id BIGINT NOT NULL REFERENCES warehouse(id)
);

CREATE TABLE aisle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    description VARCHAR(255),
    zone_id BIGINT NOT NULL REFERENCES warehouse_zone(id)
);

CREATE TABLE rack (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    description VARCHAR(255),
    aisle_id BIGINT NOT NULL REFERENCES aisle(id)
);

CREATE TABLE storage_level (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255),
    description VARCHAR(255),
    rack_id BIGINT NOT NULL REFERENCES rack(id)
);

CREATE TABLE bin_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    capacity DOUBLE PRECISION,
    active BOOLEAN NOT NULL,
    version BIGINT,
    storage_level_id BIGINT NOT NULL REFERENCES storage_level(id)
);

CREATE TABLE inventory_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT,
    sku VARCHAR(255) NOT NULL UNIQUE,
    barcode VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    weight_per_unit DOUBLE PRECISION,
    space_per_unit DOUBLE PRECISION,
    length DOUBLE PRECISION,
    width DOUBLE PRECISION,
    height DOUBLE PRECISION,
    warehouse_id BIGINT REFERENCES warehouse(id)
);

CREATE TABLE tool (
    id BIGINT PRIMARY KEY REFERENCES inventory_item(id),
    serial_number VARCHAR(255),
    maintenance_date DATE,
    is_calibrated BOOLEAN NOT NULL
);

CREATE TABLE consumable_material (
    id BIGINT PRIMARY KEY REFERENCES inventory_item(id),
    length DOUBLE PRECISION,
    material_type VARCHAR(255),
    unit VARCHAR(255)
);

CREATE TABLE stock_position (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    bin_location_id BIGINT REFERENCES bin_location(id),
    quantity INTEGER,
    reserved_quantity INTEGER,
    status VARCHAR(32),
    version BIGINT
);

ALTER TABLE stock_position ADD CONSTRAINT uq_stock_position_item_bin UNIQUE (inventory_item_id, bin_location_id);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    description VARCHAR(255),
    customer_name VARCHAR(255),
    customer_email VARCHAR(255),
    delivery_address VARCHAR(255),
    status VARCHAR(32)
);

CREATE TABLE project_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocated_quantity INTEGER,
    project_id BIGINT REFERENCES project(id),
    inventory_item_id BIGINT REFERENCES inventory_item(id)
);

CREATE TABLE pick_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES project(id),
    status VARCHAR(32),
    created_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP
);

CREATE TABLE pick_order_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_order_id BIGINT NOT NULL REFERENCES pick_order(id),
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    required_quantity INTEGER,
    picked_quantity INTEGER,
    bin_location_id BIGINT NOT NULL REFERENCES bin_location(id),
    status VARCHAR(32)
        ,shortage_quantity INTEGER
        ,shortage_reason VARCHAR(32)
        ,shortage_reported_at TIMESTAMP
        ,shortage_reported_by VARCHAR(255)
        ,shortage_note VARCHAR(255)
        ,version BIGINT
);

CREATE TABLE pick_scan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pick_order_line_id BIGINT NOT NULL REFERENCES pick_order_line(id),
    scanned_barcode VARCHAR(255),
    quantity INTEGER,
    scanned_at TIMESTAMP,
    accepted BOOLEAN NOT NULL,
    message VARCHAR(255),
    scanned_by VARCHAR(255)
);

CREATE TABLE goods_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number VARCHAR(255) NOT NULL UNIQUE,
    supplier_name VARCHAR(255),
    received_at TIMESTAMP,
    received_by VARCHAR(255),
    status VARCHAR(32)
);

CREATE TABLE goods_receipt_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goods_receipt_id BIGINT NOT NULL REFERENCES goods_receipt(id),
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    expected_quantity INTEGER,
    received_quantity INTEGER,
    bin_location_id BIGINT NOT NULL REFERENCES bin_location(id)
);

CREATE TABLE delivery_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_number VARCHAR(255) NOT NULL UNIQUE,
    pick_order_id BIGINT NOT NULL UNIQUE REFERENCES pick_order(id),
    recipient VARCHAR(255),
    delivery_address VARCHAR(255),
    created_at TIMESTAMP,
    pack_status VARCHAR(32),
    shipping_status VARCHAR(32),
    tracking_number VARCHAR(255),
    shipping_shipment_id VARCHAR(255)
);

CREATE TABLE delivery_note_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_note_id BIGINT NOT NULL REFERENCES delivery_note(id),
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    quantity INTEGER,
        shortage_quantity INTEGER,
        shortage_reason VARCHAR(32),
    bin_location_id BIGINT NOT NULL REFERENCES bin_location(id)
);

CREATE TABLE inventory_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP,
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    quantity_delta INTEGER,
    previous_quantity INTEGER,
    new_quantity INTEGER,
    reason VARCHAR(32),
    reference_type VARCHAR(255),
    reference_id BIGINT,
    username VARCHAR(255)
);

CREATE TABLE wms_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL
);

CREATE TABLE shipping_outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_note_id BIGINT,
    payload TEXT,
    status VARCHAR(32),
    error_message TEXT,
    created_at TIMESTAMP,
    next_attempt_at TIMESTAMP,
    processed_at TIMESTAMP,
    attempts INTEGER,
    version BIGINT
);

CREATE TABLE warehouse_worker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    shift VARCHAR(255),
    forklift_license BOOLEAN NOT NULL
);

CREATE TABLE project_manager (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255),
    department VARCHAR(255),
    approval_limit DOUBLE PRECISION
);
