CREATE TABLE batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_number VARCHAR(255) NOT NULL,
    supplier_lot_number VARCHAR(255),
    manufactured_at DATE,
    expiration_date DATE,
    received_at TIMESTAMP
);

CREATE TABLE unit_of_measure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(255),
    type VARCHAR(32)
);

CREATE TABLE unit_conversion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_unit_id BIGINT NOT NULL REFERENCES unit_of_measure(id),
    to_unit_id BIGINT NOT NULL REFERENCES unit_of_measure(id),
    factor NUMERIC(19,6)
);

CREATE TABLE tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255),
    active BOOLEAN NOT NULL
);

CREATE TABLE packaging_unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    name VARCHAR(255),
    quantity_in_base_unit NUMERIC(19,6),
    barcode VARCHAR(255) UNIQUE,
    length DOUBLE PRECISION,
    width DOUBLE PRECISION,
    height DOUBLE PRECISION,
    weight DOUBLE PRECISION
);

CREATE TABLE supplier_item_reference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL REFERENCES inventory_item(id),
    supplier_name VARCHAR(255),
    supplier_article_number VARCHAR(255) NOT NULL,
    supplier_barcode VARCHAR(255),
    lead_time_days INTEGER,
    preferred_supplier BOOLEAN NOT NULL,
    CONSTRAINT uq_supplier_item_reference UNIQUE (supplier_name, supplier_article_number)
);

ALTER TABLE stock_position ADD COLUMN batch_id BIGINT REFERENCES batch(id);
ALTER TABLE stock_position ADD COLUMN tenant_id BIGINT REFERENCES tenant(id);
ALTER TABLE stock_position ADD COLUMN unit_id BIGINT REFERENCES unit_of_measure(id);
ALTER TABLE stock_position ADD CONSTRAINT ck_stock_position_quantities CHECK (quantity >= 0 AND reserved_quantity >= 0 AND reserved_quantity <= quantity);

CREATE TABLE stock_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_position_id BIGINT NOT NULL REFERENCES stock_position(id),
    pick_order_id BIGINT REFERENCES pick_order(id),
    quantity INTEGER,
    status VARCHAR(32),
    created_at TIMESTAMP,
    released_at TIMESTAMP,
    fulfilled_at TIMESTAMP,
    username VARCHAR(255),
    reason VARCHAR(255),
    version BIGINT
);

CREATE TABLE inventory_adjustment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_position_id BIGINT NOT NULL REFERENCES stock_position(id),
    requested_quantity INTEGER,
    old_quantity INTEGER,
    delta INTEGER,
    reason VARCHAR(255),
    note VARCHAR(255),
    requested_by VARCHAR(255),
    requested_at TIMESTAMP,
    approved_by VARCHAR(255),
    approved_at TIMESTAMP,
    status VARCHAR(32),
    version BIGINT
);